-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.department
(
    dept_no character varying(10) NOT NULL,
    dept_name character varying(30) NOT NULL,
    PRIMARY KEY (dept_no)
);

CREATE TABLE IF NOT EXISTS public.title
(
    title_id character varying(10) NOT NULL,
    title character varying(30) NOT NULL,
    PRIMARY KEY (title_id)
);

CREATE TABLE IF NOT EXISTS public.employee
(
    emp_no integer NOT NULL,
    title_id character varying(10),
    birth_date date,
    first_name character varying(30),
    last_name character varying(30),
    sex character varying(1),
    hire_date date,
    PRIMARY KEY (emp_no)
);

CREATE TABLE IF NOT EXISTS public.dept_manager
(
    dept_no character varying(10) NOT NULL,
    emp_no integer NOT NULL,
    PRIMARY KEY (dept_no, emp_no)
);

CREATE TABLE IF NOT EXISTS public.dept_emp
(
    emp_no integer NOT NULL,
    dept_no character varying(10) NOT NULL,
    PRIMARY KEY (emp_no, dept_no)
);

CREATE TABLE IF NOT EXISTS public.salaries
(
    emp_no integer NOT NULL,
    salary money NOT NULL,
    PRIMARY KEY (emp_no)
);

ALTER TABLE IF EXISTS public.employee
    ADD CONSTRAINT fk_title FOREIGN KEY (title_id)
    REFERENCES public.title (title_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.dept_manager
    ADD CONSTRAINT fk1 FOREIGN KEY (dept_no)
    REFERENCES public.department (dept_no) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.dept_manager
    ADD CONSTRAINT fk2 FOREIGN KEY (emp_no)
    REFERENCES public.employee (emp_no) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.dept_emp
    ADD CONSTRAINT fk1 FOREIGN KEY (emp_no)
    REFERENCES public.employee (emp_no) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.dept_emp
    ADD CONSTRAINT fk2 FOREIGN KEY (dept_no)
    REFERENCES public.department (dept_no) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.salaries
    ADD CONSTRAINT fk1 FOREIGN KEY (emp_no)
    REFERENCES public.employee (emp_no) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;